hero1:
  name: "Superman"
  word: "Superman is here!"
  age: 30
  power: 100
  skills:
    - "Fly"
    - "Laser eyes"
    - "Super strength"

hero2:
  name: "Batman"
  word: "I'm Batman"
  age: 35
  power: 90
  skills:
    - "Fight"
    - "Detective"
    - "Rich"

    
hero_name: 
  - "Superman"
  - "Batman"
  - "Wonder"